server:
  port: ${PORT}
env:
  telegram:
    texts:
      path: texts/
      fileExtension: .md
      maxResourceSize: 3000
      topicEnrichmentLine: back to topics -> /topics
      goToArticleLine: go to article ->
    bot:
      name: ${BOT_NAME}
      token: ${BOT_TOKEN}
      baseUrl: https://api.telegram.org/bot
  commands:
    -
      name: fyodor1
      resourceId: bio1
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub
    -
      name: fyodor2
      resourceId: bio2
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub
    -
      name: fyodor3
      resourceId: bio3
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub
    -
      name: fyodor4
      resourceId: bio4
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub
    -
      name: dielo1
      resourceId: dielo1
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub
    -
      name: dielo2
      resourceId: dielo2
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub
    -
      name: varia
      resourceId: varia
      externalLink: https://docs.google.com/document/d/e/2PACX-1vTC49asYE2fGdMwghaTRYSPDQpuJwPTRfFphb_7o9Fr1rTKNkW7j2_h5EApLaiswgHuPUlnF6F56tM6/pub